### ISSUE TITLE
No Auth ?

### ISSUE THREAD

**Issue by LordVlad-Neutral** [Unending/Habitomate#2]
`config.read("config.ini")`

I don't python ok ? Maybe it's not a good idea to try to test out undocumented python programs then... But well, I have a lot of ideas... mostly bad ones.

Anyways... I don't know where I'm supposed to make that file, what to put in it or anything. I tried various things but it doesn't do anything. Auth always fails.

**Comment by Unending** [comment]
Create a `config.ini` file in the same directory and put the following in it:

```
[AUTH]
HABITICA_USER: your user-id
HABITICA_TOKEN: your api-token
```

**Comment by LordVlad-Neutral** [comment]
I was so close, basically, just needed to change my typo... used = and stuff. Anyways works now and they are great !
